# Generated by Django 5.1.7 on 2025-03-19 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCapacitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('url', models.TextField(null=True)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='capacitaciones', to='capacitaciones.categoriacapacitacion')),
            ],
        ),
    ]
