# Generated by Django 5.0.13 on 2025-03-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
