# Generated by Django 5.1.5 on 2025-03-27 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0002_capacitacion_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('evidencia', models.TextField(blank=True, null=True)),
                ('idCapacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='capacitaciones.capacitacion')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('idUsuario', 'idCapacitacion')},
            },
        ),
    ]
