# Generated by Django 5.1.7 on 2025-03-31 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0004_alter_registro_idcapacitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='idCapacitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='capacitaciones.capacitacion'),
        ),
    ]
